[package]
name = "iris-d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
petgraph = "0.5.1"
pest = "2"
pest_derive = "2"
